name: React CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
        env:
          CI: true

      - name: Build
        run: npm run build

      # Thêm step thông báo
      - name: Notify success
        if: success()
        run: |
          echo "✅ CI/CD completed successfully!"

      - name: Notify failure
        if: failure()
        run: |
          echo "❌ CI/CD failed!"
