name: React CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # Nâng cấp lên Node.js 18

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Notify success
        if: success()
        run: echo "✅ Build successful"

      - name: Notify failure
        if: failure()
        run: echo "❌ Build failed"
